### ISSUE TITLE
Newest Version / Patch is not working for me.

### ISSUE THREAD

**Issue by mugennoyami** [rivellathetank/la-metrum#1]
[https://i.imgur.com/8UgVZxI.png](url)

**Comment by rivellathetank** [comment]
Thanks for the bug report! Fixed here: https://github.com/rivellathetank/la-metrum/releases/tag/v1.1.1

**Comment by rivellathetank** [comment]
Have you tried it? Does it work?

**Comment by mugennoyami** [comment]
Looks good! Yes. Thanks for the fast update! <3
[https://i.imgur.com/FttlfRC.png](url)

**Comment by mugennoyami** [comment]
Okay nvm it isn't working. I can open the Programm now but it's not tracking any Damage. The time's counting upwards but apparently it's not detecting damage / zone changes etc.

**Comment by rivellathetank** [comment]
Now that's embarrassing. I introduced a bug in packaging and didn't catch it during testing because I test code *before* I package it. Should be fixed here: https://github.com/rivellathetank/la-metrum/releases/tag/v1.1.2

Thanks for reporting this issue ❤️

**Comment by mugennoyami** [comment]
All good! Thanks for the push! I'll try it out ASAP.

**Comment by mugennoyami** [comment]
Works all perfectly again. I just have an issue (which is nothing major but it also appeared before) that it doesn't show my name & ILVL but shows it for everyone else:
https://i.imgur.com/nZZgRV2.png

**Comment by romkatv** [comment]
This happens when you start the damage meter after the character has already been logged in. The name of your own character is sent by the server only when the character is logging in. If the damage meter isn't running at that point, it wont' know your name. If you go to char select and log in, you'll see your name.

Sometimes you may also see "YOU" instead of your name. This is similar. In this case the damage meter knows that it's you but still doesn't know the name. The cure is the same: go to char select and log in.

**Comment by rivellathetank** [comment]
This happens when you start the damage meter after the character has already been logged in. The name of your own character is sent by the server only during the loading screen when the character is logging in. If the damage meter isn't running at that point, it wont' know your name. If you go to char select and log in, you'll see your name.

Sometimes it may show "YOU" instead of your name. This is similar. In this case the damage meter knows that it's you but still doesn't know the name. The cure is the same: go to char select and log in.

**Comment by rivellathetank** [comment]
By the way, you can paste and drag-and-drop images directly into the github comment box. No need for imgur.

**Comment by mugennoyami** [comment]
Ah alrighty i see! Thanks! :)

Ye my screenshot tool just automatically uploads them x) so it's easier to just send the link :p
